Repository AutomationSolutionz/Zeuz_Python_Node, pull requests merged in 2022-06, with the labels that each got.

#178 [Fix] Temporary fixed appium server start
  Framework/Built_In_Automation/Mobile/CrossPlatform/Appium/BuiltInFunctions.py
Labels: action-mobile

#184 Deploy Engine v3
  .gitignore
  CHANGELOG.md
  Framework/Built_In_Automation/Sequential_Actions/sequential_actions.py
  Framework/MainDriverApi.py
  Framework/Utilities/CommonUtil.py
  Framework/Utilities/live_log_service.py
  Framework/Version.txt
  Framework/deploy_handler/__init__.py
  Framework/deploy_handler/handler.py
  Framework/deploy_handler/proto_adapter.py
  Framework/pb/__init__.py
  Framework/pb/v1/__init__.py
  Framework/pb/v1/deploy_info_message_pb2.py
  Framework/pb/v1/deploy_request_message_pb2.py
  Framework/pb/v1/deploy_response_message_pb2.py
  Framework/pb/v1/execution_report_request_message_pb2.py
  Framework/pb/v1/test_case_message_pb2.py
  Framework/settings.conf
  README.md
  node_cli.py
  requirements-linux.txt
  requirements-mac.txt
  requirements-win.txt
  requirements.txt
Labels: node-internals

#189 [Fix] Fixed screenshot common action
  CHANGELOG.md
  Framework/Built_In_Automation/Built_In_Utility/CrossPlatform/BuiltInUtilityFunction.py
Labels: action-common

#190 Do not print connection attempts
  Framework/deploy_handler/handler.py
  node_cli.py
Labels: node-internals

#191 Api cert
  CHANGELOG.md
  Framework/Built_In_Automation/Shared_Resources/BuiltInFunctionSharedResources.py
  Framework/Built_In_Automation/Web/REST/BuiltInFunctions.py
  Framework/MainDriverApi.py
  node_cli.py
Labels: action-db, node-internals

#196 Attachment hash
  .vscode/launch.json
  CHANGELOG.md
  Framework/MainDriverApi.py
  Framework/attachment_db.py
  Framework/deploy_handler/proto_adapter.py
  Framework/pb/v1/test_case_message_pb2.py
Labels: node-internals

#197 Attachment db improvements
  Framework/MainDriverApi.py
  Framework/attachment_db.py
Labels: node-internals

#200 Changed the json location to Automationlog folder
  Framework/module_installer.py
Labels: node-internals

#201 Attachment hash same content fix
  .vscode/launch.json
  Framework/MainDriverApi.py
  Framework/attachment_db.py
Labels: node-internals
